### PR TITLE
Ringtone sound, Jack detection, trigger, LED RGB

### PR DESCRIPTION
**Pull request by ernesst**
PR for : 
- Enable the ringtone sound by cleaning up the audio_platform_info
- Remove customed jack detection, as https://github.com/ubports/pulseaudio-modules-droid/commit/47bdd358eb93148d9ac5ebedf5acf76b428fdc1a manages it
- Remove bits of sound trigger : AFIAK is linked to voice detection system like google
- Remove LED RGB call that doesn't exist and polute logcat.

Still not working : 
- Volume management during call
- Switch to speaker during call.

Main PR objectif : https://github.com/ubports/ubuntu-touch/issues/1312

### CODE REVIEW

**Comment by ernesst** [comment]
@Vince1171

**Comment by Vince1171** [comment]
I don't have to time to test it, so I'll trust you

**Comment by ernesst** [comment]
When this change will land to users ? unfortunatly i couldn't find anybody else to test.

**Comment by Vince1171** [comment]
It'll land in tomorrow's update

**Comment by ernesst** [comment]
Ok cool, so we should have soon feedbacks.

**Pull request merged**
